name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Delete previous build
        run: rm -rf simpleApplication
      - name: Build & Deploy
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST }}
            USER_NAME: ${{ secrets.USER_NAME }}
            REPO_NAME: ${{ github.event.repository.name }}
            REPO_URL: ${{ github.event.repository.url }}.git
      
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME}  
          "source ./scripts/deploy.sh"
